# database
spring.datasource:
  url:
      jdbc:postgresql://127.0.0.1:5432/owncloud
  username:
    logger
  password:
    logger
  driverClassName:
    org.postgresql.Driver

# debug
spring.thymeleaf.cache: false
