# database
spring.datasource:
  url:
      jdbc:postgresql://nc_db:5432/nextcloud
  username:
    nextcloud
  password:
    nextcloud
  driverClassName:
    org.postgresql.Driver

# debug
spring.thymeleaf.cache: false
