# database
spring.datasource:
  url:
      jdbc:postgresql://ow_db:5432/owncloud
  username:
    owncloud
  password:
    owncloud
  driverClassName:
    org.postgresql.Driver

# debug
spring.thymeleaf.cache: false
